### ISSUE TITLE
Write TestCase of Stepper

### ISSUE THREAD

**Issue by uyeong** [UYEONG/stepperjs#5]
## Spec of Stepper

사용자는 Stapper 클래스의 새로운 인스턴스를 생성할 수 있다.
 - [x] new 키워드로 인스턴스를 생성하면 새로운 인스턴스가 생성된다.
 - [x] 옵션 인자를 생략하면 기본 옵션으로 설정된 인스턴스가 생성된다.
 - [x] 옵션 인자를 전달하면 전달한 옵션으로 설정된 인스턴스가 생성된다.

사용자는 stepper 객체의 option() 메서드를 이용해 옵션 값을 변경할 수 있다.
 - [x] 옵션명과 값을 전달하면 지정한 옵션이 변경된다.
 - [x] 옵션명과 값 셋을 객체로 전달하면 여러개의 옵션이 일괄로 변경된다.

사용자는 stepper 객체의 on() 메서드를 이용해 이벤트 리스너를 등록할 수 있다.
 - [x] 이벤트명과 리스너를 전달하면 지정한 이벤트 리스너가 등록된다.
 - [x] 이벤트명과 리스너 셋을 객체로 전달하면 여러개의 이벤트 리스너가 등록된다.

사용자는 stepper 객체의 off() 메서드를 이용해 이벤트 리스너를 해제할 수 있다.
 - [x] 이벤트명과 리스너를 전달하면 지정한 이벤트 리스너가 해제된다.
 - [x] 아무것도 전달하지 않으면 이벤트 리스너가 모두 해제된다.

사용자는 stepper 객체의 start() 메서드를 이용해 progress 계산을 시작할 수 있다.
 - [x] progress 계산이 시작되면 start 이벤트가 발생된다.
 - [x] duration을 1 이상 설정 했을 때만 progress 계산이 시작된다.
 - [x] 계산 중이 상태가 아닐 때만 progress 계산이 시작된다.
 - [x] progress 값이 바뀔때마다 현재 progress 값과 함께 update 이벤트가 발생된다.
 - [x] reverse 옵션을 true로 설정하면 progress 값이 거꾸로 계산된다.
 - [x] loop 옵션을 true로 설정하면 progress 계산이 반복된다.
 - [x] progress 계산이 끝나면 ended 이벤트가 발생된다.
 - [x] progress 계산이 끝나면 더이상 update 이벤트가 발생하지 않는다.

사용자는 stepper 객체의 pause() 메서드를 이용해 progress 계산을 일시 정지할 수 있다.
 - [x] progress 계산이 일시 정지 되면 paused 이벤트가 발생된다.
 - [x] 일시 정지 상태가 아닐 때만 progress 계산이 일시 정지된다.
 - [x] progress 계산이 일시 정지되면 update 이벤트가 발생하지 않는다.
 - [x] 일시 정지 상태에서 play() 메서드를 호출하면 progress 계산이 이어서 시작된다.

사용자는 stepper 객체의 stop() 메서드를 이용해 progress 계산을 중지할 수 있다.
 - [x] progress 계산이 중지되면 stoped 이벤트가 발생된다.
 - [x] 중지 상태가 아닐 때만 progress 계산이 중지된다.
 - [x] progress 계산이 중지되면 더이상 update 이벤트가 발생하지 않는다.
 - [x] 일시 중지 상태에서 stop() 메서드를 호출하면 계산이 중지된다.

**Comment by DuYongLee** [comment]
* The user should be able to make new instance of Stepper class.

    + should be made new instance.

    + should be made new instance with default option as option value is omit.

    + should be made new instance with passed option as option value is passed.

* The user should be able to change option values of stepper object.

    + should be changed separate option value

    + should be changed option values at a time

* The user should be able to attach event listener with on method

    + should be attached separate event listener

    + should be attached event listeners at a time

* The user should be able to detach event listener with off method

    + should be detached separate event listener

    + should be detached event listeners at a time

**Comment by uyeong** [comment]
@DuYongLee "~하면 ~된다." 라는 방식으로 테스트 구문을 변경했습니다. 번역에 참고하세요.

**Comment by uyeong** [comment]
Close this issue, @DuYongLee Please refer to #6 for translation.
