### ISSUE TITLE
Translate TestCase of Stepper

### ISSUE THREAD

**Issue by uyeong** [UYEONG/stepperjs#6]

**Comment by DuYongLee** [comment]
+ The user should be able to start progress calculation with start method.

  * should fire start event, when progress calculation is started.
  * should start progress calculation, only that duration is more than 1.
  * should start progress calculation, only that calculation is not processing.
  * should fire update event with current value of progress whenever value of progress is changed.
  * should calculate backwards, if value of reverse option is true.
  * should repeat progress calculation, if loop option is true.
  * should fire ended event, if progress calculation is finished.
  * should not fire update event, if progress calculation is finished.

+ The user should be able to pause progress calculation with pause method.
  * should fire paused event, when progress calculation is pause.
  * should be paused progress calculation, only that calculation state is not pause.
  * should not fire update event, if progress calculation is paused.
  * should continue progress calculation, if play method is called in pause state.


+ The user should be able to stop progress calculation with stop method.
  * should fire stopped event, when progress calculation is stopped.
  * should stop progress calculation, only that calculation state is not stop.
  * should not fire update event, if progress calculation is stopped.
  * should stop progress calculation, if stop method is called in pause state.

**Comment by DuYongLee** [comment]
Hi Uyeong, please check the comment

**Comment by uyeong** [comment]
👍  PLZ PR

**Comment by uyeong** [comment]
Thank you
